In [2]:
!python --version

Python 3.8.10


In [31]:
# Reuired library import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import RandomizedSearchCV

### step1 pbm statement

In [ ]:
# Gender classififcation

### 2 step Data Gathering


In [4]:
df= pd.read_csv('gender_classification_v7.csv')
df

long_hair  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
0             1               11.8                 6.1          1          0   
1             0               14.0                 5.4          0          0   
2             0               11.8                 6.3          1          1   
3             0               14.4                 6.1          0          1   
4             1               13.5                 5.9          0          0   
...         ...                ...                 ...        ...        ...   
4996          1               13.6                 5.1          0          0   
4997          1               11.9                 5.4          0          0   
4998          1               12.9                 5.7          0          0   
4999          1               13.2                 6.2          0          0   
5000          1               15.4                 5.4          1          1   

      lips_thin  distance_nose_to_lip_long  gender  
0             1                          1    Male  
1             1                          0  Female  
2             1                          1    Male  
3             1                          1    Male  
4             0                          0  Female  
...         ...                        ...     ...  
4996          0                          0  Female  
4997          0                          0  Female  
4998          0                          0  Female  
4999          0                          0  Female  
5000          1                          1    Male  

[5001 rows x 8 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5001 entries, 0 to 5000
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   long_hair                  5001 non-null   int64  
 1   forehead_width_cm          5001 non-null   float64
 2   forehead_height_cm         5001 non-null   float64
 3   nose_wide                  5001 non-null   int64  
 4   nose_long                  5001 non-null   int64  
 5   lips_thin                  5001 non-null   int64  
 6   distance_nose_to_lip_long  5001 non-null   int64  
 7   gender                     5001 non-null   object 
dtypes: float64(2), int64(5), object(1)
memory usage: 312.7+ KB


### step 3 EDA  & Feature Engg

In [6]:
df['gender'].unique()

array(['Male', 'Female'], dtype=object)

In [10]:
df['gender']=df['gender'].replace({'Male':1,'Female':0})


In [11]:
df['gender'].unique()

array([1, 0], dtype=int64)

### step 4 :Feature Selection

In [ ]:
# all are important

In [12]:
# Moidel Training
# data splitting
x=df.drop('gender',axis=1)
y=df['gender']
x_train,x_test,y_train,y_test =train_test_split(x,y,test_size=0.2,random_state=7,stratify=y)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(4000, 7)
(1001, 7)
(4000,)
(1001,)


In [16]:
x_train.T

4112  640   1011  881   2706  1861  2507  2659  \
long_hair                   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   
forehead_width_cm          11.9  13.5  11.8  15.4  13.1  13.7  11.9  11.8   
forehead_height_cm          5.9   6.4   6.7   7.1   6.2   5.2   5.7   6.4   
nose_wide                   0.0   1.0   1.0   1.0   1.0   1.0   0.0   0.0   
nose_long                   0.0   0.0   0.0   1.0   1.0   1.0   1.0   0.0   
lips_thin                   0.0   0.0   1.0   1.0   1.0   0.0   0.0   0.0   
distance_nose_to_lip_long   1.0   0.0   1.0   1.0   1.0   1.0   0.0   0.0   

                           2071  3204  ...  752   2613  3602  2012  4273  \
long_hair                   1.0   1.0  ...   1.0   1.0   1.0   1.0   1.0   
forehead_width_cm          14.6  12.6  ...  12.8  14.9  12.7  12.3  13.4   
forehead_height_cm          6.7   5.3  ...   6.5   6.5   6.5   6.4   5.9   
nose_wide                   1.0   0.0  ...   0.0   0.0   1.0   0.0   0.0   
nose_long                   1.0   0.0  ...   0.0   1.0   1.0   0.0   0.0   
lips_thin                   1.0   1.0  ...   1.0   1.0   1.0   0.0   1.0   
distance_nose_to_lip_long   1.0   0.0  ...   0.0   1.0   1.0   0.0   0.0   

                           1526  221   4364  3554  828   
long_hair                   0.0   1.0   0.0   1.0   0.0  
forehead_width_cm          12.0  15.3  15.1  13.1  12.9  
forehead_height_cm          5.8   6.7   5.6   5.8   6.2  
nose_wide                   0.0   0.0   1.0   0.0   0.0  
nose_long                   0.0   1.0   0.0   1.0   0.0  
lips_thin                   0.0   1.0   1.0   0.0   0.0  
distance_nose_to_lip_long   0.0   1.0   1.0   1.0   0.0  

[7 rows x 4000 columns]

In [13]:
log_model =LogisticRegression()
log_model.fit(x_train,y_train)


LogisticRegression()

In [18]:
# Modeel Evalution
y_test_pred =log_model.predict(x_test)

def mod_eval(actual,pred):
    acc=accuracy_score(actual,pred)
    cm= confusion_matrix(actual,pred)
    report=classification_report(actual,pred)
    print(f'Accuracy score={acc}')
    print(f'Confunsion Matrix=\n{cm}')
    print(f'Classfication Report=\n{report}')
    
mod_eval(y_test,y_test_pred)    

Accuracy score=0.961038961038961
Confunsion Matrix=
[[484  17]
 [ 22 478]]
Classfication Report=
              precision    recall  f1-score   support

           0       0.96      0.97      0.96       501
           1       0.97      0.96      0.96       500

    accuracy                           0.96      1001
   macro avg       0.96      0.96      0.96      1001
weighted avg       0.96      0.96      0.96      1001



In [20]:
y_train_pred =log_model.predict(x_train)
mod_eval(y_train,y_train_pred)

Accuracy score=0.96975
Confunsion Matrix=
[[1941   59]
 [  62 1938]]
Classfication Report=
              precision    recall  f1-score   support

           0       0.97      0.97      0.97      2000
           1       0.97      0.97      0.97      2000

    accuracy                           0.97      4000
   macro avg       0.97      0.97      0.97      4000
weighted avg       0.97      0.97      0.97      4000



In [ ]:
# from above testing & trainijng Acc both are same =96

In [21]:
(1941+1938)/(1941+1938+59+62)

0.96975

In [22]:
# KNN Model
std=StandardScaler()
x_std=std.fit_transform(x)
x_train,x_test,y_train,y_test =train_test_split(x_std,y,test_size=0.2,random_state=7,stratify=y)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(4000, 7)
(1001, 7)
(4000,)
(1001,)


In [23]:
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)


KNeighborsClassifier()

In [24]:
y_train_pred =knn.predict(x_train)
mod_eval(y_train,y_train_pred)

Accuracy score=0.97725
Confunsion Matrix=
[[1967   33]
 [  58 1942]]
Classfication Report=
              precision    recall  f1-score   support

           0       0.97      0.98      0.98      2000
           1       0.98      0.97      0.98      2000

    accuracy                           0.98      4000
   macro avg       0.98      0.98      0.98      4000
weighted avg       0.98      0.98      0.98      4000



In [26]:
y_test_pred =knn.predict(x_test)
mod_eval(y_test,y_test_pred)

Accuracy score=0.962037962037962
Confunsion Matrix=
[[491  10]
 [ 28 472]]
Classfication Report=
              precision    recall  f1-score   support

           0       0.95      0.98      0.96       501
           1       0.98      0.94      0.96       500

    accuracy                           0.96      1001
   macro avg       0.96      0.96      0.96      1001
weighted avg       0.96      0.96      0.96      1001



In [ ]:
#96 &97

In [27]:
# Random Forest
x=df.drop('gender',axis=1)
y=df['gender']
x_train,x_test,y_train,y_test =train_test_split(x,y,test_size=0.2,random_state=7,stratify=y)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(4000, 7)
(1001, 7)
(4000,)
(1001,)


In [28]:
rf=RandomForestClassifier(random_state=10)
rf.fit(x_train,y_train)

RandomForestClassifier(random_state=10)

In [29]:
y_test_pred =rf.predict(x_test)
mod_eval(y_test,y_test_pred)

Accuracy score=0.962037962037962
Confunsion Matrix=
[[489  12]
 [ 26 474]]
Classfication Report=
              precision    recall  f1-score   support

           0       0.95      0.98      0.96       501
           1       0.98      0.95      0.96       500

    accuracy                           0.96      1001
   macro avg       0.96      0.96      0.96      1001
weighted avg       0.96      0.96      0.96      1001



In [30]:
y_train_pred =rf.predict(x_train)
mod_eval(y_train,y_train_pred)

Accuracy score=0.999
Confunsion Matrix=
[[1999    1]
 [   3 1997]]
Classfication Report=
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2000
           1       1.00      1.00      1.00      2000

    accuracy                           1.00      4000
   macro avg       1.00      1.00      1.00      4000
weighted avg       1.00      1.00      1.00      4000



In [32]:
# Hypertune
model=RandomForestClassifier(random_state=5)
hyp={"n_estimators":np.arange(100,500,50),'criterion':['gini','entropy'],"min_samples_split":np.arange(3,8),
     'min_samples_leaf':np.arange(5,12),'bootstrap':[True,False]}
rscv= RandomizedSearchCV(model,hyp,cv=5)
rscv.fit(x_train,y_train)

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(random_state=5),
                   param_distributions={'bootstrap': [True, False],
                                        'criterion': ['gini', 'entropy'],
                                        'min_samples_leaf': array([ 5,  6,  7,  8,  9, 10, 11]),
                                        'min_samples_split': array([3, 4, 5, 6, 7]),
                                        'n_estimators': array([100, 150, 200, 250, 300, 350, 400, 450])})

In [33]:
rscv.best_estimator_

RandomForestClassifier(min_samples_leaf=5, min_samples_split=4,
                       n_estimators=150, random_state=5)

In [34]:
rf_hyp_model=rscv.best_estimator_
rf_hyp_model.fit(x_train,y_train)

RandomForestClassifier(min_samples_leaf=5, min_samples_split=4,
                       n_estimators=150, random_state=5)

In [35]:
y_train_pred =rf_hyp_model.predict(x_train)
mod_eval(y_train,y_train_pred)

Accuracy score=0.984
Confunsion Matrix=
[[1984   16]
 [  48 1952]]
Classfication Report=
              precision    recall  f1-score   support

           0       0.98      0.99      0.98      2000
           1       0.99      0.98      0.98      2000

    accuracy                           0.98      4000
   macro avg       0.98      0.98      0.98      4000
weighted avg       0.98      0.98      0.98      4000



In [36]:
y_test_pred =rf_hyp_model.predict(x_test)
mod_eval(y_test,y_test_pred)

Accuracy score=0.965034965034965
Confunsion Matrix=
[[493   8]
 [ 27 473]]
Classfication Report=
              precision    recall  f1-score   support

           0       0.95      0.98      0.97       501
           1       0.98      0.95      0.96       500

    accuracy                           0.97      1001
   macro avg       0.97      0.97      0.97      1001
weighted avg       0.97      0.97      0.97      1001



In [37]:
# Final Model >>>>>
col_list=list(x.columns)
col_dict={'column':col_list}
col_dict

{'column': ['long_hair',
  'forehead_width_cm',
  'forehead_height_cm',
  'nose_wide',
  'nose_long',
  'lips_thin',
  'distance_nose_to_lip_long']}

In [39]:
import json
with open('col_dict.json','w') as file:
    json.dump(col_dict,file)

In [40]:
import pickle
with open('model.pkl','wb') as file:
    pickle.dump(rf_hyp_model,file)

In [41]:
x.columns

Index(['long_hair', 'forehead_width_cm', 'forehead_height_cm', 'nose_wide',
       'nose_long', 'lips_thin', 'distance_nose_to_lip_long'],
      dtype='object')

In [42]:
x.head()

long_hair  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
0          1               11.8                 6.1          1          0   
1          0               14.0                 5.4          0          0   
2          0               11.8                 6.3          1          1   
3          0               14.4                 6.1          0          1   
4          1               13.5                 5.9          0          0   

   lips_thin  distance_nose_to_lip_long  
0          1                          1  
1          1                          0  
2          1                          1  
3          1                          1  
4          0                          0

In [43]:
df.head()

long_hair  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
0          1               11.8                 6.1          1          0   
1          0               14.0                 5.4          0          0   
2          0               11.8                 6.3          1          1   
3          0               14.4                 6.1          0          1   
4          1               13.5                 5.9          0          0   

   lips_thin  distance_nose_to_lip_long  gender  
0          1                          1       1  
1          1                          0       0  
2          1                          1       1  
3          1                          1       1  
4          0                          0       0

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5001 entries, 0 to 5000
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   long_hair                  5001 non-null   int64  
 1   forehead_width_cm          5001 non-null   float64
 2   forehead_height_cm         5001 non-null   float64
 3   nose_wide                  5001 non-null   int64  
 4   nose_long                  5001 non-null   int64  
 5   lips_thin                  5001 non-null   int64  
 6   distance_nose_to_lip_long  5001 non-null   int64  
 7   gender                     5001 non-null   int64  
dtypes: float64(2), int64(6)
memory usage: 312.7 KB


In [ ]:
np.array()